Repository Orange-Juice-Tech/tema-da-comunidade-dark, pull requests merged in 2024-02, with the labels that each got.

#11 configuração "sideBar.background"
  themes/Orange Juice Tech - Dark-color-theme.json
Labels: enhancement

#15 Docs/guia-contribuir
  README.md
Labels: documentation

#17 Mudanças nas cores do editor
  themes/Orange Juice Tech - Dark-color-theme.json
Labels: aprimoramento

#18 Atualização da Main com o primeiro merge da comunidade
  themes/Orange Juice Tech - Dark-color-theme.json
Labels: aprimoramento

#19 Alteração no esquema de cores do terminal
  README.md
  themes/Orange Juice Tech - Dark-color-theme.json
Labels: aprimoramento

#20 Adicionando 2o PR da comunidade a Main
  themes/Orange Juice Tech - Dark-color-theme.json
Labels: aprimoramento
